---

updates:
  - directory: /
    package-ecosystem: docker
    schedule:
      interval: weekly

  - directory: /
    package-ecosystem: docker-compose
    schedule:
      interval: weekly

  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly

  - directory: /backend
    package-ecosystem: uv
    schedule:
      interval: daily
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3

  - directory: /frontend
    package-ecosystem: npm
    schedule:
      interval: daily
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3

version: 2
