FROM docker.io/ubuntu:26.04

USER root

# Combine packages installation and configure locale in a single layer
RUN apt-get update && apt-get install --no-install-recommends -y \
        ca-certificates \
        acl \
        curl \
        gnupg2 \
        lsb-release \
        wget \
        software-properties-common \
        git \
        gh \
        vim \
        sudo \
        openssh-client \
        locales \
        build-essential \
        bind9 \
        bison \
        ccache \
        cmake \
        cppzmq-dev \
        flex \
        g++ cmake make libpcap-dev \
        libfl2 \
        libfl-dev \
        libnode-dev \
        libmaxminddb-dev \
        libpcap-dev \
        libssl-dev \
        libuv1-dev \
        libz-dev \
        libzmq5 \
    && add-apt-repository -y universe \
    && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && locale-gen en_US.UTF-8 \
    && update-locale LANG=en_US.UTF-8 \
    && rm -rf /var/lib/apt/lists/*

# Install Docker CLI and Compose V2 from Ubuntu repositories
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        docker.io \
        docker-compose-v2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy tooling from official images cleanly (automatically matches host architecture)
COPY --link --from=docker.io/zeek/zeek:8.0.5 /usr/local/zeek /usr/local/zeek

# Surgeon-copy the exact compiled version of libnode and dependent libicu libraries Zeek/V8 expects
COPY --link --from=docker.io/zeek/zeek:8.0.5 /usr/lib/*-linux-gnu/libnode.so.115* /usr/local/zeek/lib/
COPY --link --from=docker.io/zeek/zeek:8.0.5 /usr/lib/*-linux-gnu/libicu*.so.76* /usr/local/zeek/lib/

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /usr/local/bin/
COPY --link --from=ghcr.io/pnpm/pnpm:11 /opt/pnpm /usr/local/bin/

# Configure the dynamic library linker so the system can find Zeek's shared libraries natively
RUN echo "/usr/local/zeek/lib" > /etc/ld.so.conf.d/zeek.conf && ldconfig

# Copy cargo & rustup completely to ensure toolchain functions correctly
COPY --link --from=docker.io/rust:slim-trixie /usr/local/cargo /usr/local/cargo
COPY --link --from=docker.io/rust:slim-trixie /usr/local/rustup /usr/local/rustup

# Environment configurations
ENV CARGO_HOME=/usr/local/cargo
ENV RUSTUP_HOME=/usr/local/rustup
ENV PATH="/usr/local/zeek/bin:/usr/local/cargo/bin:${PATH}"
ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy
ENV LANG=en_US.UTF-8
ENV NVM_DIR=/home/elevadr/.nvm
ENV PRE_COMMIT_HOME=/workspace/.local_cache/pre-commit
ENV UV_CACHE_DIR=/workspace/.local_cache/uv
ENV PNPM_CACHE_DIR=/workspace/.local_cahce/pnpm/cache
ENV PNPM_STORE_DIR=/workspace/.local_cahce/pnpm/store

USER elevadr

WORKDIR /workspace

EXPOSE 8000
CMD ["sleep", "infinity"]
