"""Local MongoDB runtime configuration helpers for eleVADR Stage 1B."""
from __future__ import annotations

import argparse
import secrets
from pathlib import Path
from urllib.parse import quote_plus

ROOT = Path(__file__).resolve().parents[2]
ENV_PATH = ROOT / ".elevadr-platform.env"
DEFAULT_ROOT_USER = "elevadr_root"
DEFAULT_PORT = 27017


def _secret(length: int = 48) -> str:
    # URL-safe alphanumeric credentials avoid URI/Compose quoting surprises.
    alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    return "".join(secrets.choice(alphabet) for _ in range(length))


def build_mongodb_uri(username: str, password: str, port: int = DEFAULT_PORT) -> str:
    return (
        f"mongodb://{quote_plus(username)}:{quote_plus(password)}@127.0.0.1:{port}/"
        "?authSource=admin&directConnection=true"
    )


def render_env(root_username: str, root_password: str, jwt_secret: str, port: int) -> str:
    uri = build_mongodb_uri(root_username, root_password, port)
    return "\n".join([
        "# Generated by eleVADR Stage 1B. Do not commit this file.",
        "# Authentication remains disabled until the login UI stage is deliberately enabled.",
        f"ELEVADR_MONGO_ROOT_USERNAME={root_username}",
        f"ELEVADR_MONGO_ROOT_PASSWORD={root_password}",
        f"ELEVADR_MONGO_PORT={port}",
        f"ELEVADR_MONGODB_URI={uri}",
        "ELEVADR_MONGODB_DATABASE=elevadr",
        "ELEVADR_AUTH_ENABLED=false",
        f"ELEVADR_JWT_SECRET={jwt_secret}",
        "ELEVADR_JWT_ALGORITHM=HS256",
        "ELEVADR_JWT_EXPIRE_MINUTES=60",
        "",
    ])


def write_env(path: Path = ENV_PATH, *, force: bool = False) -> Path:
    if path.exists() and not force:
        raise FileExistsError(f"{path.name} already exists; use --force to replace it")
    path.write_text(render_env(DEFAULT_ROOT_USER, _secret(), _secret(64), DEFAULT_PORT), encoding="utf-8")
    return path


def load_env(path: Path = ENV_PATH) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key] = value
    return values


def main() -> int:
    parser = argparse.ArgumentParser(description="Manage eleVADR local platform runtime configuration")
    sub = parser.add_subparsers(dest="command", required=True)
    init = sub.add_parser("init", help="create .elevadr-platform.env with random local secrets")
    init.add_argument("--force", action="store_true")
    sub.add_parser("show-uri", help="print the configured local MongoDB URI")
    args = parser.parse_args()
    if args.command == "init":
        try:
            path = write_env(force=args.force)
        except FileExistsError as exc:
            print(f"INFO: {exc}")
            return 0
        print(f"Created {path}")
        return 0
    values = load_env()
    print(values.get("ELEVADR_MONGODB_URI", ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
