---
name: Publish Docker Image

on: # yamllint disable-line rule:truthy
  release:
    types:
      - created

jobs:
  diagnostics:
    name: Run diagnostics
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - name: Apply standard cisagov job preamble
        uses: cisagov/action-job-preamble@v1
        with:
          monitor_permissions: "false"
          output_workflow_context: "true"
          permissions_monitoring_config: ${{ vars.ACTIONS_PERMISSIONS_CONFIG }}

  repo-metadata:
    name: Gather repository metadata
    needs:
      - diagnostics
    permissions:
      contents: read
    uses: ./.github/workflows/_repo-metadata.yml

  prepare:
    name: Prepare build variables
    needs:
      - diagnostics
      - repo-metadata
    outputs:
      labels: ${{ steps.generate-metadata.outputs.labels }}
      # We generate the image name here to use in the publish job
      image_name: ${{ needs.repo-metadata.outputs.image-name }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Apply standard cisagov job preamble
        uses: cisagov/action-job-preamble@v1
        with:
          monitor_permissions: "false"
          permissions_monitoring_config: ${{ vars.ACTIONS_PERMISSIONS_CONFIG }}
      - uses: actions/checkout@v6
      - id: generate-metadata
        name: Generate Docker image labels
        uses: docker/metadata-action@v6
        with:
          images: |
            ${{ needs.repo-metadata.outputs.image-name }}
          tags: |
            type=semver,pattern={{version}}

  publish:
    runs-on: ubuntu-latest
    needs:
      - diagnostics
      - repo-metadata
      - prepare
    permissions:
      contents: read
      packages: write
    steps:
      - name: Apply standard cisagov job preamble
        uses: cisagov/action-job-preamble@v1
        with:
          monitor_permissions: "false"
          permissions_monitoring_config: ${{ vars.ACTIONS_PERMISSIONS_CONFIG }}
      - uses: actions/checkout@v6

      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: |
            ${{ needs.prepare.outputs.image_name }}:latest
            ${{ needs.prepare.outputs.image_name }}:
            ${{ github.event.release.tag_name }}
            ghcr.io/${{ needs.prepare.outputs.image_name }}:latest
            ghcr.io/${{ needs.prepare.outputs.image_name }}:
            ${{ github.event.release.tag_name }}
          labels: ${{ needs.prepare.outputs.labels }}
          platforms: >-
            ${{ join(fromJSON(needs.repo-metadata.outputs.image-platforms)) }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
